const flash = document.getElementById("flash");
const ordersList = document.getElementById("orders-list");

// Generated by GitHub Copilot
function setFlash(message, isError = false) {
  flash.textContent = message;
  flash.style.color = isError ? "#8b2500" : "#145d35";
}

// Generated by GitHub Copilot
function renderOrders(items) {
  if (!items.length) {
    ordersList.innerHTML = "<li>No orders yet.</li>";
    return;
  }

  ordersList.innerHTML = items
    .map(
      (order) => `
        <li>
          <strong>${order.customerName}</strong> · ${order.size} · ${order.crust}<br />
          Toppings: ${order.toppings.join(", ") || "none"}<br />
          Status: ${order.status} · Total: $${order.total}
        </li>
      `
    )
    .join("");
}

// Generated by GitHub Copilot
async function refreshOrders() {
  const response = await fetch("/api/orders");
  const payload = await response.json();
  renderOrders(payload.items || []);
}

document.getElementById("refresh-orders").addEventListener("click", async () => {
  try {
    await refreshOrders();
    setFlash("Order list refreshed");
  } catch (error) {
    setFlash("Failed to load orders", true);
  }
});

document.getElementById("order-form").addEventListener("submit", async (event) => {
  event.preventDefault();

  const body = {
    customerName: document.getElementById("customer-name").value.trim(),
    size: document.getElementById("size").value,
    crust: document.getElementById("crust").value,
    toppings: document
      .getElementById("toppings")
      .value.split(",")
      .map((item) => item.trim())
      .filter(Boolean),
    paymentMethod: document.getElementById("payment-method").value,
  };

  try {
    const response = await fetch("/api/orders", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });

    const payload = await response.json();
    if (!response.ok) {
      throw new Error(payload.detail || "Order failed");
    }

    setFlash(`Order placed for ${payload.customerName}`);
    event.target.reset();
    await refreshOrders();
  } catch (error) {
    setFlash(error.message || "Order creation failed", true);
  }
});

refreshOrders().catch(() => {
  setFlash("Unable to load orders on startup", true);
});
