// Generated by GitHub Copilot
import express from "express";
import cors from "cors";
import { v4 as uuidv4 } from "uuid";

import { reserveInventory, snapshotInventory } from "./services/inventory.js";
import { processPayment } from "./services/payment.js";
import { calculateTotal, canTransitionStatus } from "./services/orders.js";

const app = express();
const PORT = Number(process.env.PORT || 8080);

app.use(cors());
app.use(express.json());
app.use(express.static("frontend"));

const menu = [
  { id: "margherita", name: "Margherita", suggestedToppings: ["basil", "extra_cheese"] },
  { id: "farmhouse", name: "Farmhouse", suggestedToppings: ["onion", "mushroom", "capsicum"] },
  { id: "pepperoni", name: "Pepperoni", suggestedToppings: ["pepperoni", "jalapeno"] },
];

const inventory = {
  basil: 25,
  extra_cheese: 30,
  onion: 40,
  mushroom: 35,
  capsicum: 32,
  pepperoni: 18,
  jalapeno: 22,
  olives: 26,
  paneer: 20,
};

const orders = [];

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "pizzeria-fullstack-ordering-platform",
    totalOrders: orders.length,
  });
});

app.get("/api/menu", (_req, res) => {
  res.json({ menu, inventory: snapshotInventory(inventory) });
});

app.get("/api/orders", (_req, res) => {
  res.json({ items: orders });
});

app.post("/api/orders", (req, res) => {
  const { customerName, size, crust, toppings, paymentMethod } = req.body ?? {};

  if (!customerName || !size || !crust || !Array.isArray(toppings) || !paymentMethod) {
    return res.status(422).json({ detail: "customerName, size, crust, toppings, and paymentMethod are required" });
  }

  const reserved = reserveInventory(toppings, inventory);
  if (!reserved.ok) {
    return res.status(409).json({ detail: "Inventory unavailable", missing: reserved.missing });
  }

  const total = calculateTotal(size, toppings);
  const payment = processPayment(total, String(paymentMethod).toLowerCase());
  if (!payment.approved) {
    return res.status(402).json({ detail: "Payment rejected" });
  }

  const order = {
    id: uuidv4(),
    customerName,
    size,
    crust,
    toppings,
    status: "placed",
    total,
    payment,
    createdAt: new Date().toISOString(),
  };

  orders.push(order);
  return res.status(201).json(order);
});

app.patch("/api/orders/:id/status", (req, res) => {
  const order = orders.find((item) => item.id === req.params.id);
  if (!order) {
    return res.status(404).json({ detail: "Order not found" });
  }

  const nextStatus = req.body?.status;
  if (!nextStatus || !canTransitionStatus(order.status, nextStatus)) {
    return res.status(422).json({ detail: "Invalid status transition" });
  }

  order.status = nextStatus;
  order.updatedAt = new Date().toISOString();
  return res.json(order);
});

app.listen(PORT, () => {
  // Keeping startup log concise for local MVP usage.
  // eslint-disable-next-line no-console
  console.log(`Pizzeria app listening on http://127.0.0.1:${PORT}`);
});
