// Generated by GitHub Copilot
import express from "express";
import cors from "cors";
import { v4 as uuidv4 } from "uuid";
import { fileURLToPath } from "node:url";

import { reserveInventory, snapshotInventory } from "./services/inventory.js";
import { processPayment } from "./services/payment.js";
import { calculateTotal, canTransitionStatus } from "./services/orders.js";

const app = express();
const PORT = Number(process.env.PORT || 8080);

app.use(cors());
app.use(express.json());
app.use(express.static("frontend"));

// Generated by GitHub Copilot
/**
 * Attaches request correlation id and baseline security headers.
 */
app.use((req, res, next) => {
  const requestId = req.get("X-Request-ID") || uuidv4();
  req.requestId = requestId;
  res.setHeader("X-Request-ID", requestId);
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("X-Frame-Options", "DENY");
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  next();
});

const menu = [
  { id: "margherita", name: "Margherita", suggestedToppings: ["basil", "extra_cheese"] },
  { id: "farmhouse", name: "Farmhouse", suggestedToppings: ["onion", "mushroom", "capsicum"] },
  { id: "pepperoni", name: "Pepperoni", suggestedToppings: ["pepperoni", "jalapeno"] },
];

const INITIAL_INVENTORY = {
  basil: 25,
  extra_cheese: 30,
  onion: 40,
  mushroom: 35,
  capsicum: 32,
  pepperoni: 18,
  jalapeno: 22,
  olives: 26,
  paneer: 20,
};

const inventory = {};
const orders = [];
const rateLimitBuckets = new Map();

const DEFAULT_RATE_LIMIT_MAX = 60;
const DEFAULT_RATE_LIMIT_WINDOW_MS = 60_000;

// Generated by GitHub Copilot
/**
 * Resolves or creates a request id for the current request lifecycle.
 * @param {import('express').Request} req
 * @returns {string}
 */
function getRequestId(req) {
  const stateRequestId = req.requestId;
  if (typeof stateRequestId === "string" && stateRequestId.length > 0) {
    return stateRequestId;
  }

  const headerRequestId = req.get("X-Request-ID");
  if (headerRequestId && headerRequestId.length > 0) {
    return headerRequestId;
  }

  return uuidv4();
}

// Generated by GitHub Copilot
/**
 * Maps HTTP status values to stable API error codes.
 * @param {number} status
 * @returns {string}
 */
function statusToErrorCode(status) {
  const mapping = {
    400: "bad_request",
    401: "unauthorized",
    402: "payment_required",
    404: "not_found",
    409: "conflict",
    413: "payload_too_large",
    422: "validation_error",
    429: "rate_limited",
  };

  if (status >= 500) {
    return "internal_error";
  }
  return mapping[status] ?? "request_failed";
}

// Generated by GitHub Copilot
/**
 * Creates normalized error payload used across API responses.
 * @param {import('express').Request} req
 * @param {string} code
 * @param {string} message
 * @param {unknown} [details]
 * @returns {{ error: { code: string, message: string, request_id: string, details?: unknown } }}
 */
function buildErrorPayload(req, code, message, details) {
  const payload = {
    error: {
      code,
      message,
      request_id: getRequestId(req),
    },
  };

  if (details !== undefined) {
    payload.error.details = details;
  }
  return payload;
}

// Generated by GitHub Copilot
/**
 * Sends a normalized error response with optional extra headers.
 * @param {import('express').Request} req
 * @param {import('express').Response} res
 * @param {number} status
 * @param {string} message
 * @param {unknown} [details]
 * @param {Record<string, string>} [extraHeaders]
 * @returns {void}
 */
function sendError(req, res, status, message, details, extraHeaders = undefined) {
  if (extraHeaders) {
    for (const [key, value] of Object.entries(extraHeaders)) {
      res.setHeader(key, value);
    }
  }

  res.status(status).json(
    buildErrorPayload(
      req,
      statusToErrorCode(status),
      message,
      details,
    ),
  );
}

// Generated by GitHub Copilot
/**
 * Parses a positive integer environment variable with fallback.
 * @param {string} name - Environment variable name.
 * @param {number} fallback - Default numeric value.
 * @returns {number} Parsed positive integer or fallback.
 */
function readPositiveIntEnv(name, fallback) {
  const raw = process.env[name];
  const parsed = Number.parseInt(raw ?? `${fallback}`, 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    return fallback;
  }
  return parsed;
}

// Generated by GitHub Copilot
/**
 * Returns configured API key for protected write operations.
 * @returns {string} Configured API key value or empty string.
 */
function getConfiguredApiKey() {
  return String(process.env.API_KEY ?? "").trim();
}

// Generated by GitHub Copilot
/**
 * Enforces API key auth on mutating endpoints when API_KEY is configured.
 * @param {import('express').Request} req - Incoming request.
 * @param {import('express').Response} res - Outgoing response.
 * @param {import('express').NextFunction} next - Next middleware handler.
 * @returns {void}
 */
function requireApiKey(req, res, next) {
  const configuredApiKey = getConfiguredApiKey();
  if (!configuredApiKey) {
    next();
    return;
  }

  const providedApiKey = req.get("x-api-key");
  if (providedApiKey !== configuredApiKey) {
    sendError(req, res, 401, "api_key_invalid");
    return;
  }

  next();
}

// Generated by GitHub Copilot
/**
 * Applies a lightweight in-memory fixed-window rate limit by client and path.
 * @param {import('express').Request} req - Incoming request.
 * @param {import('express').Response} res - Outgoing response.
 * @param {import('express').NextFunction} next - Next middleware handler.
 * @returns {void}
 */
function enforceRateLimit(req, res, next) {
  const maxRequests = readPositiveIntEnv("RATE_LIMIT_MAX", DEFAULT_RATE_LIMIT_MAX);
  const windowMs = readPositiveIntEnv("RATE_LIMIT_WINDOW_MS", DEFAULT_RATE_LIMIT_WINDOW_MS);

  const now = Date.now();
  const key = `${req.ip}:${req.path}`;
  const bucket = rateLimitBuckets.get(key) ?? [];
  const cutoff = now - windowMs;
  const activeWindow = bucket.filter((timestamp) => timestamp >= cutoff);

  if (activeWindow.length >= maxRequests) {
    sendError(req, res, 429, "rate_limited", undefined, { "Retry-After": "60" });
    return;
  }

  activeWindow.push(now);
  rateLimitBuckets.set(key, activeWindow);
  next();
}

const writeGuards = [requireApiKey, enforceRateLimit];

// Generated by GitHub Copilot
/**
 * Resets mutable in-memory app state between runs and tests.
 * @returns {void}
 */
export function resetAppState() {
  orders.length = 0;
  rateLimitBuckets.clear();
  for (const key of Object.keys(inventory)) {
    delete inventory[key];
  }
  Object.assign(inventory, INITIAL_INVENTORY);
}

resetAppState();

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "pizzeria-fullstack-ordering-platform",
    totalOrders: orders.length,
  });
});

app.get("/ready", (_req, res) => {
  res.json({
    status: "ready",
    service: "pizzeria-fullstack-ordering-platform",
  });
});

app.get("/healthz", (_req, res) => {
  res.json({
    status: "ok",
    service: "pizzeria-fullstack-ordering-platform",
    totalOrders: orders.length,
  });
});

app.get("/readyz", (_req, res) => {
  res.json({
    status: "ready",
    service: "pizzeria-fullstack-ordering-platform",
  });
});

app.get("/api/menu", (_req, res) => {
  res.json({ menu, inventory: snapshotInventory(inventory) });
});

app.get("/api/orders", (_req, res) => {
  res.json({ items: orders });
});

app.post("/api/orders", writeGuards, (req, res) => {
  const { customerName, size, crust, toppings, paymentMethod } = req.body ?? {};

  if (!customerName || !size || !crust || !Array.isArray(toppings) || !paymentMethod) {
    sendError(req, res, 422, "request_validation_failed");
    return;
  }

  const reserved = reserveInventory(toppings, inventory);
  if (!reserved.ok) {
    sendError(req, res, 409, "inventory_unavailable", { missing: reserved.missing });
    return;
  }

  const total = calculateTotal(size, toppings);
  const payment = processPayment(total, String(paymentMethod).toLowerCase());
  if (!payment.approved) {
    sendError(req, res, 402, "payment_rejected");
    return;
  }

  const order = {
    id: uuidv4(),
    customerName,
    size,
    crust,
    toppings,
    status: "placed",
    total,
    payment,
    createdAt: new Date().toISOString(),
  };

  orders.push(order);
  return res.status(201).json(order);
});

app.patch("/api/orders/:id/status", writeGuards, (req, res) => {
  const order = orders.find((item) => item.id === req.params.id);
  if (!order) {
    sendError(req, res, 404, "order_not_found");
    return;
  }

  const nextStatus = req.body?.status;
  if (!nextStatus || !canTransitionStatus(order.status, nextStatus)) {
    sendError(req, res, 422, "invalid_status_transition");
    return;
  }

  order.status = nextStatus;
  order.updatedAt = new Date().toISOString();
  return res.json(order);
});

app.use((req, res) => {
  sendError(req, res, 404, "route_not_found");
});

// Generated by GitHub Copilot
/**
 * Returns true when the module is executed directly instead of imported.
 * @returns {boolean}
 */
function isMainModule() {
  return Boolean(process.argv[1]) && fileURLToPath(import.meta.url) === process.argv[1];
}

if (isMainModule()) {
  app.listen(PORT, () => {
    // Keeping startup log concise for local MVP usage.
    // eslint-disable-next-line no-console
    console.log(`Pizzeria app listening on http://127.0.0.1:${PORT}`);
  });
}

export { app };
