// Generated by GitHub Copilot

/**
 * Verifies topping inventory and decrements stock when an order is accepted.
 * @param {string[]} toppings - Requested topping list.
 * @param {Record<string, number>} inventory - Mutable inventory map.
 * @returns {{ok: boolean, missing: string[]}} Result object.
 */
export function reserveInventory(toppings, inventory) {
  const missing = toppings.filter((topping) => !inventory[topping] || inventory[topping] <= 0);
  if (missing.length > 0) {
    return { ok: false, missing };
  }

  for (const topping of toppings) {
    inventory[topping] -= 1;
  }

  return { ok: true, missing: [] };
}

/**
 * Returns a copy of available inventory values.
 * @param {Record<string, number>} inventory - Inventory map.
 * @returns {Record<string, number>} Snapshot object.
 */
export function snapshotInventory(inventory) {
  return { ...inventory };
}
