// Generated by GitHub Copilot

const SIZE_BASE = {
  small: 7,
  medium: 10,
  large: 13,
};

/**
 * Calculates order total from selected size and toppings.
 * @param {string} size - Pizza size.
 * @param {string[]} toppings - Topping list.
 * @returns {number} Total amount.
 */
export function calculateTotal(size, toppings) {
  const base = SIZE_BASE[size] ?? SIZE_BASE.medium;
  const toppingsCost = (toppings?.length ?? 0) * 1.5;
  return Number((base + toppingsCost).toFixed(2));
}

/**
 * Returns true if status transition is allowed for MVP order lifecycle.
 * @param {string} currentStatus - Existing status value.
 * @param {string} nextStatus - Proposed status value.
 * @returns {boolean} Transition validity.
 */
export function canTransitionStatus(currentStatus, nextStatus) {
  const order = ["placed", "preparing", "baking", "out_for_delivery", "delivered", "cancelled"];
  const currentIndex = order.indexOf(currentStatus);
  const nextIndex = order.indexOf(nextStatus);

  if (currentIndex === -1 || nextIndex === -1) {
    return false;
  }

  if (currentStatus === "cancelled" || currentStatus === "delivered") {
    return false;
  }

  return nextIndex >= currentIndex;
}
