// Generated by GitHub Copilot

/**
 * Simulates a payment processor response for MVP usage.
 * @param {number} amount - Order total amount.
 * @param {string} method - Payment method text.
 * @returns {{approved: boolean, transactionId: string, amount: number, method: string}} Result object.
 */
export function processPayment(amount, method) {
  const approved = amount > 0 && ["card", "upi", "wallet", "cash"].includes(method);
  return {
    approved,
    transactionId: approved ? `txn_${Math.random().toString(36).slice(2, 10)}` : "",
    amount,
    method,
  };
}
