// Generated by GitHub Copilot
import test from "node:test";
import assert from "node:assert/strict";
import request from "supertest";

import { app, resetAppState } from "../index.js";

// Generated by GitHub Copilot
/**
 * Builds a valid order payload for API integration tests.
 * @param {Partial<{customerName: string, size: string, crust: string, toppings: string[], paymentMethod: string}>} overrides
 * @returns {{customerName: string, size: string, crust: string, toppings: string[], paymentMethod: string}}
 */
function buildOrderPayload(overrides = {}) {
  return {
    customerName: "Demo User",
    size: "medium",
    crust: "thin",
    toppings: ["basil", "olives"],
    paymentMethod: "card",
    ...overrides,
  };
}

// Generated by GitHub Copilot
/**
 * Temporarily sets process environment values for a test and restores them afterwards.
 * @param {Record<string, string | undefined>} nextValues
 * @param {() => Promise<void>} run
 * @returns {Promise<void>}
 */
async function withEnv(nextValues, run) {
  const previousValues = {};
  for (const [key, value] of Object.entries(nextValues)) {
    previousValues[key] = process.env[key];
    if (value === undefined) {
      delete process.env[key];
    } else {
      process.env[key] = value;
    }
  }

  try {
    await run();
  } finally {
    for (const [key, value] of Object.entries(previousValues)) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
    resetAppState();
  }
}

test("creates an order and returns it in order list", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());

  assert.equal(createResponse.status, 201);
  assert.equal(createResponse.body.status, "placed");
  assert.ok(createResponse.body.id);

  const listResponse = await request(app).get("/api/orders");

  assert.equal(listResponse.status, 200);
  assert.equal(Array.isArray(listResponse.body.items), true);
  assert.equal(listResponse.body.items.length, 1);
});

test("rejects order creation when required fields are missing", async () => {
  resetAppState();

  const response = await request(app).post("/api/orders").send({
    customerName: "Demo User",
    size: "medium",
  });

  assert.equal(response.status, 422);
  assert.match(response.body.detail, /required/i);
});

test("updates status when transition is valid", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());
  const orderId = createResponse.body.id;

  const patchResponse = await request(app)
    .patch(`/api/orders/${orderId}/status`)
    .send({ status: "preparing" });

  assert.equal(patchResponse.status, 200);
  assert.equal(patchResponse.body.status, "preparing");
});

test("requires X-API-Key on write endpoints when API_KEY is configured", async () => {
  await withEnv({ API_KEY: "secret-key" }, async () => {
    resetAppState();

    const unauthorized = await request(app).post("/api/orders").send(buildOrderPayload());
    assert.equal(unauthorized.status, 401);

    const authorized = await request(app)
      .post("/api/orders")
      .set("X-API-Key", "secret-key")
      .send(buildOrderPayload());

    assert.equal(authorized.status, 201);
  });
});

test("rate limits write requests when threshold is exceeded", async () => {
  await withEnv(
    {
      API_KEY: "secret-key",
      RATE_LIMIT_MAX: "2",
      RATE_LIMIT_WINDOW_MS: "60000",
    },
    async () => {
      resetAppState();

      const first = await request(app)
        .post("/api/orders")
        .set("X-API-Key", "secret-key")
        .send(buildOrderPayload({ customerName: "Demo One" }));
      const second = await request(app)
        .post("/api/orders")
        .set("X-API-Key", "secret-key")
        .send(buildOrderPayload({ customerName: "Demo Two" }));
      const third = await request(app)
        .post("/api/orders")
        .set("X-API-Key", "secret-key")
        .send(buildOrderPayload({ customerName: "Demo Three" }));

      assert.equal(first.status, 201);
      assert.equal(second.status, 201);
      assert.equal(third.status, 429);
    },
  );
});
