// Generated by GitHub Copilot
import test from "node:test";
import assert from "node:assert/strict";
import request from "supertest";

import { app, resetAppState } from "../index.js";

// Generated by GitHub Copilot
/**
 * Builds a valid order payload for API integration tests.
 * @param {Partial<{customerName: string, size: string, crust: string, toppings: string[], paymentMethod: string}>} overrides
 * @returns {{customerName: string, size: string, crust: string, toppings: string[], paymentMethod: string}}
 */
function buildOrderPayload(overrides = {}) {
  return {
    customerName: "Demo User",
    size: "medium",
    crust: "thin",
    toppings: ["basil", "olives"],
    paymentMethod: "card",
    ...overrides,
  };
}

test("creates an order and returns it in order list", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());

  assert.equal(createResponse.status, 201);
  assert.equal(createResponse.body.status, "placed");
  assert.ok(createResponse.body.id);

  const listResponse = await request(app).get("/api/orders");

  assert.equal(listResponse.status, 200);
  assert.equal(Array.isArray(listResponse.body.items), true);
  assert.equal(listResponse.body.items.length, 1);
});

test("rejects order creation when required fields are missing", async () => {
  resetAppState();

  const response = await request(app).post("/api/orders").send({
    customerName: "Demo User",
    size: "medium",
  });

  assert.equal(response.status, 422);
  assert.match(response.body.detail, /required/i);
});

test("updates status when transition is valid", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());
  const orderId = createResponse.body.id;

  const patchResponse = await request(app)
    .patch(`/api/orders/${orderId}/status`)
    .send({ status: "preparing" });

  assert.equal(patchResponse.status, 200);
  assert.equal(patchResponse.body.status, "preparing");
});
