// Generated by GitHub Copilot
import test from "node:test";
import assert from "node:assert/strict";
import request from "supertest";

import { app, resetAppState } from "../index.js";

// Generated by GitHub Copilot
/**
 * Asserts standardized API error response contract.
 * @param {import('supertest').Response} response
 * @param {{status: number, code: string, message?: string, details?: boolean}} expected
 */
function assertErrorContract(response, expected) {
  assert.equal(response.status, expected.status);
  assert.equal(typeof response.body?.error, "object");
  assert.equal(response.body.error.code, expected.code);
  assert.equal(typeof response.body.error.message, "string");
  if (expected.message !== undefined) {
    assert.equal(response.body.error.message, expected.message);
  }
  assert.equal(typeof response.body.error.request_id, "string");
  assert.ok(response.body.error.request_id.length > 0);
  if (expected.details === true) {
    assert.equal(typeof response.body.error.details, "object");
  }
}

// Generated by GitHub Copilot
/**
 * Builds a valid order payload for API integration tests.
 * @param {Partial<{customerName: string, size: string, crust: string, toppings: string[], paymentMethod: string}>} overrides
 * @returns {{customerName: string, size: string, crust: string, toppings: string[], paymentMethod: string}}
 */
function buildOrderPayload(overrides = {}) {
  return {
    customerName: "Demo User",
    size: "medium",
    crust: "thin",
    toppings: ["basil", "olives"],
    paymentMethod: "card",
    ...overrides,
  };
}

// Generated by GitHub Copilot
/**
 * Temporarily sets process environment values for a test and restores them afterwards.
 * @param {Record<string, string | undefined>} nextValues
 * @param {() => Promise<void>} run
 * @returns {Promise<void>}
 */
async function withEnv(nextValues, run) {
  const previousValues = {};
  for (const [key, value] of Object.entries(nextValues)) {
    previousValues[key] = process.env[key];
    if (value === undefined) {
      delete process.env[key];
    } else {
      process.env[key] = value;
    }
  }

  try {
    await run();
  } finally {
    for (const [key, value] of Object.entries(previousValues)) {
      if (value === undefined) {
        delete process.env[key];
      } else {
        process.env[key] = value;
      }
    }
    resetAppState();
  }
}

test("creates an order and returns it in order list", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());

  assert.equal(createResponse.status, 201);
  assert.equal(createResponse.body.status, "placed");
  assert.ok(createResponse.body.id);

  const listResponse = await request(app).get("/api/orders");

  assert.equal(listResponse.status, 200);
  assert.equal(Array.isArray(listResponse.body.items), true);
  assert.equal(listResponse.body.items.length, 1);
});

test("exposes Pizzaria catalog endpoints", async () => {
  resetAppState();

  const pizzasResponse = await request(app).get("/api/pizzas");
  assert.equal(pizzasResponse.status, 200);
  assert.equal(Array.isArray(pizzasResponse.body.pizzas), true);
  assert.ok(pizzasResponse.body.pizzas.length > 0);

  const toppingsResponse = await request(app).get("/api/toppings");
  assert.equal(toppingsResponse.status, 200);
  assert.equal(Array.isArray(toppingsResponse.body.toppings), true);
  assert.ok(toppingsResponse.body.toppings.length > 0);
});

test("creates and fetches a cart-style order payload", async () => {
  resetAppState();

  const menuResponse = await request(app).get("/api/pizzas");
  const firstPizza = menuResponse.body.pizzas[0];

  const createResponse = await request(app)
    .post("/api/orders")
    .send({
      customer: {
        name: "Cart User",
        phone: "9999999999",
        address: "Main Street 12",
      },
      notes: "No onions",
      paymentMethod: "card",
      items: [
        {
          pizzaId: firstPizza.id,
          quantity: 2,
        },
      ],
    });

  assert.equal(createResponse.status, 201);
  assert.equal(createResponse.body.status, "placed");
  assert.equal(createResponse.body.customer.name, "Cart User");
  assert.equal(Array.isArray(createResponse.body.items), true);
  assert.equal(createResponse.body.items.length, 1);
  assert.ok(createResponse.body.pricing.total > 0);

  const getOrderResponse = await request(app).get(`/api/orders/${createResponse.body.id}`);
  assert.equal(getOrderResponse.status, 200);
  assert.equal(getOrderResponse.body.order.id, createResponse.body.id);
});

test("exposes readiness and probe alias endpoints", async () => {
  resetAppState();

  const ready = await request(app).get("/ready");
  assert.equal(ready.status, 200);
  assert.equal(ready.body.status, "ready");

  const healthz = await request(app).get("/healthz");
  assert.equal(healthz.status, 200);
  assert.equal(healthz.body.status, "ok");

  const readyz = await request(app).get("/readyz");
  assert.equal(readyz.status, 200);
  assert.equal(readyz.body.status, "ready");
});

test("rejects order creation when required fields are missing", async () => {
  resetAppState();

  const response = await request(app).post("/api/orders").send({
    customerName: "Demo User",
    size: "medium",
  });

  assertErrorContract(response, {
    status: 422,
    code: "validation_error",
    message: "request_validation_failed",
  });
});

test("updates status when transition is valid", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());
  const orderId = createResponse.body.id;

  const patchResponse = await request(app)
    .patch(`/api/orders/${orderId}/status`)
    .send({ status: "preparing" });

  assert.equal(patchResponse.status, 200);
  assert.equal(patchResponse.body.status, "preparing");
});

test("auto-advances status when patch payload is empty", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());
  const orderId = createResponse.body.id;

  const patchResponse = await request(app)
    .patch(`/api/orders/${orderId}/status`)
    .send({});

  assert.equal(patchResponse.status, 200);
  assert.equal(patchResponse.body.status, "preparing");
});

test("requires X-API-Key on write endpoints when API_KEY is configured", async () => {
  await withEnv({ API_KEY: "secret-key" }, async () => {
    resetAppState();

    const unauthorized = await request(app).post("/api/orders").send(buildOrderPayload());
    assertErrorContract(unauthorized, {
      status: 401,
      code: "unauthorized",
      message: "api_key_invalid",
    });

    const authorized = await request(app)
      .post("/api/orders")
      .set("X-API-Key", "secret-key")
      .send(buildOrderPayload());

    assert.equal(authorized.status, 201);
  });
});

test("rate limits write requests when threshold is exceeded", async () => {
  await withEnv(
    {
      API_KEY: "secret-key",
      RATE_LIMIT_MAX: "2",
      RATE_LIMIT_WINDOW_MS: "60000",
    },
    async () => {
      resetAppState();

      const first = await request(app)
        .post("/api/orders")
        .set("X-API-Key", "secret-key")
        .send(buildOrderPayload({ customerName: "Demo One" }));
      const second = await request(app)
        .post("/api/orders")
        .set("X-API-Key", "secret-key")
        .send(buildOrderPayload({ customerName: "Demo Two" }));
      const third = await request(app)
        .post("/api/orders")
        .set("X-API-Key", "secret-key")
        .send(buildOrderPayload({ customerName: "Demo Three" }));

      assert.equal(first.status, 201);
      assert.equal(second.status, 201);
      assertErrorContract(third, {
        status: 429,
        code: "rate_limited",
        message: "rate_limited",
      });
      assert.equal(third.headers["retry-after"], "60");
    },
  );
});

test("error responses include request and security headers", async () => {
  await withEnv({ API_KEY: "header-secret" }, async () => {
    const response = await request(app).post("/api/orders").send(buildOrderPayload());

    assert.equal(response.status, 401);
    assert.equal(typeof response.headers["x-request-id"], "string");
    assert.equal(response.headers["x-content-type-options"], "nosniff");
    assert.equal(response.headers["x-frame-options"], "DENY");
  });
});

test("returns normalized not-found contract for unknown routes", async () => {
  resetAppState();

  const response = await request(app).get("/api/does-not-exist");
  assertErrorContract(response, {
    status: 404,
    code: "not_found",
    message: "route_not_found",
  });
});

test("rejects status transition with unknown status value", async () => {
  resetAppState();

  const createResponse = await request(app).post("/api/orders").send(buildOrderPayload());
  const orderId = createResponse.body.id;

  const invalidTransition = await request(app)
    .patch(`/api/orders/${orderId}/status`)
    .send({ status: "packed" });

  assertErrorContract(invalidTransition, {
    status: 422,
    code: "validation_error",
    message: "invalid_status_transition",
  });
});

test("rejects order when payment method is unsupported", async () => {
  resetAppState();

  const response = await request(app)
    .post("/api/orders")
    .send(buildOrderPayload({ paymentMethod: "bank_transfer" }));

  assertErrorContract(response, {
    status: 402,
    code: "payment_required",
    message: "payment_rejected",
  });
});

test("returns inventory conflict when requested toppings exceed stock", async () => {
  resetAppState();

  const heavyPepperoniPayload = buildOrderPayload({
    toppings: Array.from({ length: 30 }, () => "pepperoni"),
  });

  const response = await request(app).post("/api/orders").send(heavyPepperoniPayload);

  assertErrorContract(response, {
    status: 409,
    code: "conflict",
    message: "inventory_unavailable",
    details: true,
  });
  assert.equal(Array.isArray(response.body.error.details.missing), true);
  assert.equal(response.body.error.details.missing.includes("pepperoni"), true);
});
