// Generated by GitHub Copilot
import test from "node:test";
import assert from "node:assert/strict";

import { canTransitionStatus } from "../services/orders.js";

test("allows forward lifecycle transitions", () => {
  assert.equal(canTransitionStatus("placed", "preparing"), true);
  assert.equal(canTransitionStatus("preparing", "baking"), true);
  assert.equal(canTransitionStatus("baking", "out_for_delivery"), true);
  assert.equal(canTransitionStatus("out_for_delivery", "delivered"), true);
});

test("rejects unknown statuses", () => {
  assert.equal(canTransitionStatus("unknown", "preparing"), false);
  assert.equal(canTransitionStatus("placed", "unknown"), false);
});

test("rejects transitions from terminal states", () => {
  assert.equal(canTransitionStatus("cancelled", "preparing"), false);
  assert.equal(canTransitionStatus("delivered", "placed"), false);
});
